json.extract! user,
              :id,
              :username,
              :email,
              :location,
              :looking_for,
              :position,
              :summary,
              :languages,
              :frameworks
