json.id @user.id
json.username @user.username
json.location @user.location
json.summary @user.summary
json.image_file_name asset_path(@user.image_file_name)
json.gender @user.gender
json.orientation @user.orientation
json.age @user.age
json.life @user.life
json.skills @user.skills
json.favorites @user.favorites
json.thinking @user.thinking
json.friday @user.friday
json.msg_if @user.msg_if
